#!/usr/bin/env node
/**
 * precompute_g_powers.js
 * 
 * Generates hardcoded powers of 2 for the Ed25519 base point G
 * Output: 2^0·G, 2^1·G, 2^2·G, ..., 2^254·G
 * 
 * These precomputed values eliminate the need for point doubling operations
 * in the fixed-base scalar multiplication, reducing constraints by ~70%
 */

const { Point } = require('@noble/ed25519');
const fs = require('fs');

// Ed25519 base point G
const G = Point.BASE;

console.log('Computing powers of 2 for Ed25519 base point G...');
console.log('This will generate 255 precomputed points (2^0·G through 2^254·G)\n');

// Function to convert a point to extended coordinates in base 2^85
// Ed25519 uses p = 2^255 - 19
// We represent field elements in base 2^85 (3 limbs of 85 bits each)
function pointToExtendedCoords(point) {
    // Get affine coordinates
    const affine = point.toAffine();
    const x = affine.x;
    const y = affine.y;
    
    // Extended coordinates: (X:Y:Z:T) where x=X/Z, y=Y/Z, xy=T/Z
    // For affine point (x, y), extended is (x:y:1:xy)
    
    // Convert to base 2^85 representation
    // This is a simplified version - in production, use proper bigint arithmetic
    
    // For now, we'll output in hex and let the circuit handle conversion
    return {
        x: '0x' + x.toString(16),
        y: '0x' + y.toString(16),
        // In extended coords: Z=1, T=x*y mod p
        z: '0x1',
        t: '0x' + ((x * y) % Point.CURVE.Fp.ORDER).toString(16)
    };
}

// Compute powers
const powers = [];
let current = G;

for (let i = 0; i < 255; i++) {
    const coords = pointToExtendedCoords(current);
    powers.push({
        index: i,
        scalar: `2^${i}`,
        coords: coords
    });
    
    if (i % 10 === 0) {
        console.log(`Computed 2^${i}·G`);
    }
    
    // Double for next iteration
    current = current.double();
}

console.log('\nGeneration complete!\n');

// Generate Circom function code
let circomCode = `// AUTOGENERATED by precompute_g_powers.js
// DO NOT EDIT MANUALLY
//
// Precomputed powers of 2 for Ed25519 base point G
// Format: Extended coordinates (X:Y:Z:T) in hexadecimal
// These values eliminate ~700K constraints from fixed-base scalar multiplication

pragma circom 2.1.0;

function get_G_powers_of_2() {
    // Returns array[255][4] where each entry is [X, Y, Z, T] in hex
    // To use in circuit, convert to base 2^85 representation
    
    var powers[255][4];
    
`;

for (let i = 0; i < powers.length; i++) {
    const p = powers[i];
    circomCode += `    // 2^${i}·G\n`;
    circomCode += `    powers[${i}][0] = ${p.coords.x}; // X\n`;
    circomCode += `    powers[${i}][1] = ${p.coords.y}; // Y\n`;
    circomCode += `    powers[${i}][2] = ${p.coords.z}; // Z\n`;
    circomCode += `    powers[${i}][3] = ${p.coords.t}; // T\n`;
    circomCode += `\n`;
}

circomCode += `    return powers;
}
`;

// Write to file
const outputPath = './lib/ed25519/g_powers_precomputed.circom';
fs.writeFileSync(outputPath, circomCode);

console.log(`✅ Precomputed values written to: ${outputPath}`);
console.log(`📊 Generated ${powers.length} precomputed points`);
console.log(`💾 File size: ${(circomCode.length / 1024).toFixed(2)} KB`);
console.log(`\n⚡ Estimated constraint reduction: ~700,000 constraints`);
console.log(`   (Eliminates all point doubling operations in R = r·G computation)\n`);
